### PR TITLE
First pass wrapping input to show form-note

### PR DESCRIPTION
**Pull request by daverau-optimizely**
@inakiaranzadi-optimizely This is my quick attempt to add form-notes to the input react component, but I feel there is probably a more thoughtful approach similar to the way label is handled. I'm curious your thoughts here!

screenshot 2017-07-03 13 26 02

### CODE REVIEW

**Comment by inakiaranzadi-optimizely** [comment]
How can we avoid repeating `.oui-form-bad-news` class when `hasError` is true and it have a `label` prop happening?

```html
<div class="oui-form-bad-news">
  <label>
    <div class="oui-label"><!-- react-text: 7 -->adfadf<!-- /react-text --></div>
    <input type="text" min="10" max="50" class="oui-text-input oui-form-bad-news" value="some default value" placeholder="just a placeholder">
  </label>
</div>
```

**Comment by inakiaranzadi-optimizely** [comment]
Also we are styling label with a wrapper. I wonder if passing props to `<Label />` is a better more scalable alternative. What do you think @daverau-optimizely?

**Comment by daverau-optimizely** [comment]
This latest push updates Label to handle displayError along with some minor CSS changes. Updating tests now.

screenshot 2017-07-06 15 54 47

**Comment by inakiaranzadi-optimizely** [comment]
@daverau-optimizely  I think the build is failing because os some `lint` warning and errors.

**Pull request merged**
