### PR TITLE
Rename `core` to `oui`

### PR DESCRIPTION
**Pull request by tomgenoni**
@danoc This changes all references of `core` to `oui`.

### CODE REVIEW

**Comment by danoc** [comment]
Going to wait until we merge #187 to do a pass on this.

**Comment by danoc** [comment]
@tomgenoni – I made some changes. Take a look.

Although I don't think renaming `src/core/` to `src/oui/` (instead of `src/scss/`) makes it more clear for users importing OUI since the imports already point into `node_modules/oui/`.

**Comment by tomgenoni** [comment]
It makes it clearer for users integrating it with gulp/grunt because now their root.scss file will look like:

```
@import 'oui/oui-variables';
@import 'design-dot/design-dot-variables';

@import 'oui/oui-partials';
@import 'design-dot/design-dot-partials';
```

The partial paths will now all start with their origins.

**Comment by danoc** [comment]
Hmmm... Those imports would work because of the `importPath` is set to point to `node_modules/`?

**Comment by tomgenoni** [comment]
Yes, but it's not hardcoded. OUI exports the path to itself for other projects to use. `includePath` points to its `src`.

**Pull request merged**
