### PR TITLE
fix(tokensInput): Tighten spacing around keyword tokens

### PR DESCRIPTION
**Pull request by ayeshakmaz**
Introduced a new prop for Tokens: `hasSnugWrap` which adds a tighter wrap around the Token. This new prop is then used for the tokens inside the TokensInput component

Before:

flat-before

stacked-before

After:

flatafter
stackedafter

Jira
[REC-758](https://optimizely.atlassian.net/browse/REC-758)

### CODE REVIEW

**Comment by jamesopti** [comment]
Do we want these changes to apply to all `<Tokens>`? There are many consumers of `Token` that arent the `TokensInput`.

**Comment by daverau-optimizely** [comment]
I feel bad for requesting changes here! Just a code style thing for us at Optimizely.

**Comment by daverau-optimizely** [comment]
Good call James. Ayesha and I talked about making a mini component to address the font size and padding changes and TokenInput would use miniTokens. Also Tokens will be renamed to Pills soon, but that's coming late this quarter or early next.

**Comment by ayeshakmaz** [comment]
@daverau-optimizely @jamesopti Made some updates - now TokensInput uses a smaller wrap on the Tokens. Let me know what you think

**Pull request merged**
