### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by danoc**
Using the a version of the LICENSE we use on he design-dot site. Renamed Optimizely Design Manual "ODM" to OUI.

Relates to: #125

### CODE REVIEW

**Comment by bhamodi** [comment]
LGTM. We should get a license file in this repo. However, get the Legal team to approve it. I ran into issues earlier when making license file changes without Legal team approval. :+1:

**Comment by tomgenoni** [comment]
@danoc Didn't we have legal approve it already?

**Comment by danoc** [comment]
Yup! They wrote this one for us.

**Comment by tomgenoni** [comment]
LGTM

**Comment by bhamodi** [comment]
There's a merge conflict in `changelog.md` @danoc!

**Comment by danoc** [comment]
Yup! I'll resolve it once I get a chance.

**Comment by bhamodi** [comment]
:+1:

**Comment by bhamodi** [comment]
Hey @danoc - I rebased for you. :)
Merging in now because @tomgenoni already gave the LGTM. :+1:

**Pull request merged**
