### PR TITLE
Removing extra BEM selector.

### LINKED ISSUE #343: Tab css not outputting correctly due to small error
In https://github.com/optimizely/oui/commit/7d1fc9672bfeadfd5bf00a2d4fc2ad5dcdceae3f when adding the `namespace` variable the BEM selector was accidentally also added. This causes the CSS to output `tabs-pane__item__item`.

### PR DESCRIPTION
**Pull request by tomgenoni**
Fixes #343 

@danoc

### CODE REVIEW

**Comment by tomgenoni** [comment]
@kwalker3690

**Comment by danoc** [comment]
@tomgenoni – Change log item is in the wrong place. LGTM otherwise.

**Comment by tomgenoni** [comment]
@danoc How so? Shouldn't it be under "Fixed"?

**Comment by danoc** [comment]
@tomgenoni – Ended up under 10.0.0!

**Pull request merged**
