### PR TITLE
Add React components to OUI

### PR DESCRIPTION
**Pull request by danoc**
This pull request adds React to the OUI codebase, includes a few OUI React components, and makes a few other modifications. See https://github.com/optimizely/oui/issues/378 or go/react-doc (internal only) for more context.

##### New React components

We have dozens of components to create, but these are the first that we tackled.

- ArrowsInline
- Attention
- Button
- Code
- Input
- Label

Next steps should be to create a prioritized list of components that need to be created.

##### Improved Testing: ESLint and Jest

All components include tests that live within the `<ComponentName>/tests` folder and are run with Jest. The linter was also extended to add the ESLint React plugin. These are run in Travis CI and can be run manually with the `npm test` command.

##### Faster `npm install` for projects that use OUI

We have tons of `devDependencies` that get unnecessarily downloaded by repositories that use OUI. This PR includes a change to remove the `devDependencies` from `package.json` right before publishing to NPM so that projects using OUI only get the packages they need.

##### Auto generated documentation that gets republished on deploy

We use JSDoc and [react-docgen](https://github.com/reactjs/react-docgen) to automatically generate documentation that gets deployed by Travis CI on the release of a new version.

Run `npm run react-docs:serve` locally to view the documentation.

##### Adopting the `oui-` class prefix

I've written a bit about the [importance of namespacing all of our classes](https://github.com/optimizely/oui/issues/361) with `oui-` and am [using the move to React](https://github.com/optimizely/oui/issues/361#issuecomment-213478237) as an opportunity to kickstart the process.

In practice, this means that OUI React components will only use classes that begin with the `oui-` prefix. See a few of the components in this PR for examples.

##### How to run this branch locally

1. Checkout the branch
2. `npm install`
3. `npm run react:serve`

##### How the build + development environment works

OUI uses webpack and Babel to convert our React components and ES6 into plain vanilla JS. It performs this compilations when running `npm run react:serve` locally and right before publishing to NPM. The latter allows us to use these tools without requiring other repos to download them.

##### To-do in this PR:

- [x] Update markdown files to include information about React
- [x] Add @daverau-optimizely's automatic documentation generator

*** 
@daverau-optimizely, @jordangarcia, @kwalker3690 – Can you please take a look? When reviewing, feel free to skip over the `example/*.html` files. Those were just find-and-replace and not critical.

### CODE REVIEW

**Comment by kwalker3690** [comment]
Are the only SCSS changes adding `oui-` prefixes to classes that have a namespace on them already? It's a bit hard to see if classes may have been changed to add an `oui-` prefix where there wasn't a namespace before, and would then break.

In the future, I'd say we should break down PR's like this into smaller chunks, like we could have made the scss changes first, then (depending on how interlocked these things are) the dev tools changes so that by the time we wanted to add the react components those fundamentals would already be there. It's pretty tough to diligently code review these many changes! 

That being said, I've checked out the new docs in both places and every thing seems to be compiling well. Awesome work! I'm stoked to start implementing more of these components and getting them out into the wild of Optimizely's product. But I still agree with what you said about labeling this release as beta so that we can accurately check out all of these updates.

**Comment by kwalker3690** [comment]
Oh also update the changelog!

**Comment by danoc** [comment]
@kwalker3690 – Yeah, +1 on breaking these into smaller diffs in the future.

The `oui-` prefix shouldn't break any existing things, I think, because it isn't replacing any of the old class names. It's simply another available class. Eventually there will be a breaking change where we remove the non-oui prefixed classes.

**Comment by danoc** [comment]
This PR does the following:

> ### Added
> - [Release] Add React to the OUI codebase. (#378)
> - [Release] Add Jest and the ESLint React plugin. (#378)
> - [Release] Add automatically generated React component documentation that gets deployed when new versions are released.
> - [Release] Create six React components: ArrowsInline, Attention, Button, Code, Input, and Label. (#378)
> - [Feature] Begin prefixing classes that React uses with the `oui-` prefix. (#361)
> 
> ### Changed
> - [Patch] Update `CONTRIBUTING.md` to include information about updating Optimizely's `package.json` after a release. (#408)
> - [Patch] Remove `devDependencies` before publishing OUI to NPM to increase speed of `npm install` for applications using OUI. (#356)
> - [Patch] Change release process guidelines to make upgrades less painful. (#360)
> 
> ### Fixed
> - [Patch] Add note to `README.md` saying that ScribeSass is internal only. (#359)
> - [Patch] Take a pass through our markdown files and update outdated information.

Got a 👍 on Slack and going to merge it once the tests pass.

**Pull request merged**
